# [prune]

ignored = [
  "common",
  "init",
  "k8s-health",
  "lock"
]

[[constraint]]
  name = "k8s.io/client-go"
  version = "0.18.0"

[[constraint]]
  name = "k8s.io/api"
  version = "0.18.0"

#[[constraint]]
#  branch = "master"
#  name = "k8s.io/apimachinery"
#

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[prune]
  go-tests = true
  unused-packages = true
